my word

diff --git a/script/atom-ci-install b/script/atom-ci-install
--- a/script/atom-ci-install
+++ b/script/atom-ci-install
@@ -27,6 +27,8 @@ elif [ "${TRAVIS_OS_NAME}" = "linux" ]; then
   curl -s -L "https://atom.io/download/deb?channel=${ATOM_CHANNEL}" \
     -H 'Accept: application/octet-stream' \
     -o "atom-amd64.deb"
+  # /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16
+  # export DISPLAY=":99"
   dpkg-deb -x atom-amd64.deb "${HOME}/atom"
   if [ "${ATOM_CHANNEL}" = "stable" ]; then
     export ATOM_SCRIPT_NAME="atom"
@@ -39,6 +41,50 @@ elif [ "${TRAVIS_OS_NAME}" = "linux" ]; then
   export APM_SCRIPT_PATH="${HOME}/atom/usr/bin/${APM_SCRIPT_NAME}"
   export NPM_SCRIPT_PATH="${HOME}/atom/usr/share/${ATOM_SCRIPT_NAME}/resources/app/apm/node_modules/.bin/npm"
   export PATH="${PATH}:${HOME}/atom/usr/bin"
+elif [ "${CIRCLECI}" = "true" ]; then
+  case "${CIRCLE_BUILD_IMAGE}" in
+    osx)
+      curl -s -L "https://atom.io/download/mac?channel=${ATOM_CHANNEL}" \
+        -H 'Accept: application/octet-stream' \
+        -o "atom.zip"
+      mkdir -p /tmp/atom
+      unzip -q atom.zip -d /tmp/atom
+      if [ "${ATOM_CHANNEL}" = "stable" ]; then
+        export ATOM_APP_NAME="Atom.app"
+        export ATOM_SCRIPT_NAME="atom.sh"
+        export ATOM_SCRIPT_PATH="/tmp/atom/${ATOM_APP_NAME}/Contents/Resources/app/atom.sh"
+      else
+        export ATOM_APP_NAME="Atom ${ATOM_CHANNEL}.app"
+        export ATOM_SCRIPT_NAME="atom-${ATOM_CHANNEL}"
+        export ATOM_SCRIPT_PATH="/tmp/atom-${ATOM_CHANNEL}"
+        ln -s "/tmp/atom/${ATOM_APP_NAME}/Contents/Resources/app/atom.sh" "${ATOM_SCRIPT_PATH}"
+      fi
+      export ATOM_PATH="/tmp/atom"
+      export APM_SCRIPT_PATH="/tmp/atom/${ATOM_APP_NAME}/Contents/Resources/app/apm/node_modules/.bin/apm"
+      export NPM_SCRIPT_PATH="/tmp/atom/${ATOM_APP_NAME}/Contents/Resources/app/apm/node_modules/.bin/npm"
+      export PATH="${PATH}:${TRAVIS_BUILD_DIR}/atom/${ATOM_APP_NAME}/Contents/Resources/app/apm/node_modules/.bin"
+
+      # Clear screen saver
+      osascript -e 'tell application "System Events" to keystroke "x"'
+      ;;
+    *)
+      # Assume the build is on a Debian based image (Circle CI provided Linux images)
+      curl -s -L "https://atom.io/download/deb?channel=${ATOM_CHANNEL}" \
+        -H 'Accept: application/octet-stream' \
+        -o "atom-amd64.deb"
+      sudo dpkg --install atom-amd64.deb || true
+      sudo apt-get update
+      sudo apt-get --fix-broken --assume-yes --quiet install
+      if [ "${ATOM_CHANNEL}" = "stable" ] || [ "${ATOM_CHANNEL}" = "dev" ]; then
+        export ATOM_SCRIPT_PATH="atom"
+        export APM_SCRIPT_PATH="apm"
+      else
+        export ATOM_SCRIPT_PATH="atom-${ATOM_CHANNEL}"
+        export APM_SCRIPT_PATH="apm-${ATOM_CHANNEL}"
+      fi
+      export NPM_SCRIPT_PATH="/usr/share/atom/resources/app/apm/node_modules/.bin/npm"
+      ;;
+    esac
 else
   echo "Unknown CI environment, exiting!"
   exit 1
@@ -63,6 +109,11 @@ if [ "${ATOM_LINT_WITH_BUNDLED_NODE:=true}" = "true" ]; then
   # Override the PATH to put the Node bundled with APM first
   if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
     export PATH="./atom/${ATOM_APP_NAME}/Contents/Resources/app/apm/bin:${PATH}"
+  elif [ "${CIRCLECI}" = "true" ] && [ "${CIRCLE_BUILD_IMAGE}" = "osx" ]; then
+    export PATH="/tmp/atom/${ATOM_APP_NAME}/Contents/Resources/app/apm/bin:${PATH}"
+  elif [ "${CIRCLECI}" = "true" ]; then
+    # Since CircleCI/Linux is a fully installed environment, we use the system path to apm
+    export PATH="/usr/share/atom/resources/app/apm/bin:${PATH}"
   else
     export PATH="${HOME}/atom/usr/share/${ATOM_SCRIPT_NAME}/resources/app/apm/bin:${PATH}"
   fi
@@ -75,17 +126,31 @@ else
     "${APM_SCRIPT_PATH}" install --production
     "${APM_SCRIPT_PATH}" clean
   fi
+
+  # Use the system NPM to install the devDependencies
+  echo "Using Node version:"
+  node --version
+  echo "Using NPM version:"
+  npm --version
+  echo "Installing remaining dependencies..."
+  npm install
 fi
 
-# Use the system NPM to install the devDependencies
-echo "Using Node version:"
-node --version
-echo "Using NPM version:"
-npm --version
-echo "Installing remaining dependencies..."
-npm install
+if [ -n "${APM_TEST_PACKAGES}" ]; then
+  echo "Installing atom package dependencies..."
+  for pack in ${APM_TEST_PACKAGES}; do
+    "${APM_SCRIPT_PATH}" install "${pack}"
+  done
+fi
 
-echo "Running specs..."
-"${ATOM_SCRIPT_PATH}" --test spec
-
+if [ -d ./spec ]; then
+  echo "Running specs..."
+  "${ATOM_SCRIPT_PATH}" --test spec
+elif [ -d ./test ]; then
+  echo "Running specs..."
+  "${ATOM_SCRIPT_PATH}" --test test
+else
+  echo "Missing spec folder! Please consider adding a test suite in './spec' or in './test'"
+  exit 0
+fi
 exit
